"""Role-neutral local contest generated by overlapping rival harvest.

No attack action, faction label or preferred strategy is introduced.  A
contest exists only when different current social coalitions simultaneously
extract overlapping raw channels from the same physical cell.  Ungrouped
entities are independent coalitions.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import numpy as np

from se.cfg import SimulationConfig

CONTEST_SCHEMA = "co-located-harvest-contest-v1"
DEPLETION_PRESSURE_SCHEMA = "rival-harvest-depletion-pressure-v2"
RESOURCE_CHANNELS = 4


@dataclass(frozen=True)
class HarvestContestResult:
    actor_indices: np.ndarray
    pressure: np.ndarray
    energy_cost: np.ndarray
    integrity_damage: np.ndarray
    danger_evidence: np.ndarray

    @classmethod
    def empty(cls) -> "HarvestContestResult":
        return cls(
            actor_indices=np.empty(0, dtype=np.int32),
            pressure=np.empty(0, dtype=np.float32),
            energy_cost=np.empty(0, dtype=np.float32),
            integrity_damage=np.empty(0, dtype=np.float32),
            danger_evidence=np.empty(0, dtype=np.float32),
        )

    @property
    def event_count(self) -> int:
        return int(np.count_nonzero(self.pressure > 0.0))


def resource_contest_enabled(cfg: SimulationConfig) -> bool:
    return cfg.entities.resource_contest_schema in {
        CONTEST_SCHEMA,
        DEPLETION_PRESSURE_SCHEMA,
    }


def decay_recent_contest_pressure(entities: Any, cfg: SimulationConfig) -> None:
    if not resource_contest_enabled(cfg):
        return
    entities.recent_contest_pressure *= np.float32(
        cfg.entities.resource_contest_pressure_retention
    )
    entities.recent_contest_pressure[~entities.alive] = 0.0


def resolve_harvest_contest(
    *,
    actor_indices: np.ndarray,
    cell_ids: np.ndarray,
    gathered: np.ndarray,
    group_ids: np.ndarray,
    stable_ids: np.ndarray,
    cfg: SimulationConfig,
) -> HarvestContestResult:
    actors = np.asarray(actor_indices, dtype=np.int32)
    cells = np.asarray(cell_ids, dtype=np.int64)
    amounts = np.asarray(gathered, dtype=np.float64)
    if actors.size == 0 or not resource_contest_enabled(cfg):
        return HarvestContestResult.empty()
    if cells.shape != (actors.size,) or amounts.shape != (actors.size, RESOURCE_CHANNELS):
        raise ValueError("contest inputs must align with harvest actors")
    groups = np.asarray(group_ids, dtype=np.uint64)[actors]
    ids = np.asarray(stable_ids, dtype=np.uint64)[actors]
    # Namespace coalition kind explicitly so a group token can never collide
    # with an ungrouped stable entity id.
    kinds = (groups == 0).astype(np.uint8)
    coalitions = np.where(groups != 0, groups, ids)
    key_dtype = np.dtype([("cell", np.int64), ("kind", np.uint8), ("coalition", np.uint64)])
    keys = np.empty(actors.size, dtype=key_dtype)
    keys["cell"] = cells
    keys["kind"] = kinds
    keys["coalition"] = coalitions
    unique_keys, inverse = np.unique(keys, return_inverse=True)
    coalition_totals = np.zeros((unique_keys.size, RESOURCE_CHANNELS), dtype=np.float64)
    np.add.at(coalition_totals, inverse, amounts)

    radius = int(cfg.entities.resource_contest_radius_cells)
    if radius == 0:
        unique_cells, cell_inverse = np.unique(cells, return_inverse=True)
        cell_totals = np.zeros((unique_cells.size, RESOURCE_CHANNELS), dtype=np.float64)
        np.add.at(cell_totals, cell_inverse, amounts)
        rival = np.maximum(cell_totals[cell_inverse] - coalition_totals[inverse], 0.0)
    else:
        grid_x = int(cfg.world.grid_x)
        grid_y = int(cfg.world.grid_y)
        cell_x = cells % grid_x
        cell_y = cells // grid_x
        dx = np.abs(cell_x[:, None] - cell_x[None, :])
        dy = np.abs(cell_y[:, None] - cell_y[None, :])
        if cfg.world.periodic:
            dx = np.minimum(dx, grid_x - dx)
            dy = np.minimum(dy, grid_y - dy)
        nearby = (dx <= radius) & (dy <= radius)
        same_coalition = (kinds[:, None] == kinds[None, :]) & (
            coalitions[:, None] == coalitions[None, :]
        )
        rival_mask = nearby & ~same_coalition
        rival = rival_mask.astype(np.float64) @ amounts
    own_total = amounts.sum(axis=1)
    overlap = np.minimum(amounts, rival).sum(axis=1)
    pressure = np.divide(
        overlap,
        np.maximum(own_total, 1.0e-12),
        out=np.zeros_like(overlap),
        where=own_total > 0.0,
    )
    pressure = np.clip(pressure, 0.0, 1.0).astype(np.float32)
    if cfg.entities.resource_contest_schema == DEPLETION_PRESSURE_SCHEMA:
        # Actual resource depletion has already been committed by the harvest
        # resolver.  v2 records rival overlap as physical scarcity/pressure but
        # adds no synthetic body damage or duplicate energy penalty.
        energy = np.zeros_like(pressure, dtype=np.float32)
        damage = np.zeros_like(pressure, dtype=np.float32)
        danger_evidence = np.zeros_like(pressure, dtype=np.float32)
    else:
        energy = pressure * np.float32(
            cfg.entities.resource_contest_energy_cost_per_pressure
        )
        damage = pressure * np.float32(
            cfg.entities.resource_contest_integrity_damage_per_pressure
        )
        danger_evidence = pressure
    return HarvestContestResult(
        actor_indices=actors,
        pressure=pressure,
        energy_cost=energy.astype(np.float32),
        integrity_damage=damage.astype(np.float32),
        danger_evidence=danger_evidence.astype(np.float32),
    )


def commit_harvest_contest(
    entities: Any,
    result: HarvestContestResult,
) -> None:
    if result.actor_indices.size == 0:
        return
    actors = result.actor_indices
    entities.energy[actors] -= result.energy_cost
    entities.integrity[actors] -= result.integrity_damage
    entities.recent_contest_pressure[actors] = np.maximum(
        entities.recent_contest_pressure[actors], result.pressure
    )
    # The existing danger memory coordinate is a physical observation cache,
    # not a reward.  Contest exposure joins other local danger evidence.
    entities.memory[actors, 2] = np.maximum(
        entities.memory[actors, 2], result.danger_evidence
    )


__all__ = [
    "CONTEST_SCHEMA",
    "DEPLETION_PRESSURE_SCHEMA",
    "HarvestContestResult",
    "commit_harvest_contest",
    "decay_recent_contest_pressure",
    "resolve_harvest_contest",
    "resource_contest_enabled",
]
