#pragma once
#include <cstdarg>
#include <cstddef>
#include <cstdint>

struct Vector2 { float x; float y; };
struct Rectangle { float x; float y; float width; float height; };
struct Color { unsigned char r; unsigned char g; unsigned char b; unsigned char a; };
struct Image { void* data; int width; int height; int mipmaps; int format; };
struct Texture2D { unsigned int id; int width; int height; int mipmaps; int format; };
struct Camera2D { Vector2 offset; Vector2 target; float rotation; float zoom; };
struct Shader { unsigned int id; int* locs; };
struct GlyphInfo { int value; int offsetX; int offsetY; int advanceX; Image image; };
struct Font { int baseSize; int glyphCount; int glyphPadding; Texture2D texture; Rectangle* recs; GlyphInfo* glyphs; };

inline constexpr Color LIGHTGRAY{200,200,200,255};
inline constexpr Color GRAY{130,130,130,255};
inline constexpr Color DARKGRAY{80,80,80,255};
inline constexpr Color YELLOW{253,249,0,255};
inline constexpr Color GOLD{255,203,0,255};
inline constexpr Color ORANGE{255,161,0,255};
inline constexpr Color PINK{255,109,194,255};
inline constexpr Color RED{230,41,55,255};
inline constexpr Color MAROON{190,33,55,255};
inline constexpr Color GREEN{0,228,48,255};
inline constexpr Color LIME{0,158,47,255};
inline constexpr Color DARKGREEN{0,117,44,255};
inline constexpr Color SKYBLUE{102,191,255,255};
inline constexpr Color BLUE{0,121,241,255};
inline constexpr Color DARKBLUE{0,82,172,255};
inline constexpr Color PURPLE{200,122,255,255};
inline constexpr Color VIOLET{135,60,190,255};
inline constexpr Color DARKPURPLE{112,31,126,255};
inline constexpr Color BEIGE{211,176,131,255};
inline constexpr Color BROWN{127,106,79,255};
inline constexpr Color DARKBROWN{76,63,47,255};
inline constexpr Color WHITE{255,255,255,255};
inline constexpr Color BLACK{0,0,0,255};
inline constexpr Color BLANK{0,0,0,0};
inline constexpr Color MAGENTA{255,0,255,255};
inline constexpr Color RAYWHITE{245,245,245,255};

inline constexpr int TEXTURE_FILTER_POINT = 0;
inline constexpr int TEXTURE_FILTER_BILINEAR = 1;
inline constexpr int SHADER_UNIFORM_FLOAT = 0;
inline constexpr int SHADER_UNIFORM_VEC2 = 1;
inline constexpr unsigned int FLAG_WINDOW_RESIZABLE = 0x00000004;
inline constexpr unsigned int FLAG_MSAA_4X_HINT = 0x00000020;
inline constexpr unsigned int FLAG_VSYNC_HINT = 0x00000040;
inline constexpr int MOUSE_BUTTON_LEFT = 0;
inline constexpr int MOUSE_BUTTON_MIDDLE = 2;
inline constexpr int KEY_ONE = 49;
inline constexpr int KEY_TWO = 50;
inline constexpr int KEY_THREE = 51;
inline constexpr int KEY_FOUR = 52;
inline constexpr int KEY_E = 69;
inline constexpr int KEY_H = 72;
inline constexpr int KEY_T = 84;
inline constexpr int KEY_P = 80;
inline constexpr int KEY_C = 67;
inline constexpr int KEY_B = 66;
inline constexpr int KEY_A = 65;
inline constexpr int KEY_N = 78;
inline constexpr int KEY_Y = 89;
inline constexpr int KEY_U = 85;
inline constexpr int KEY_SPACE = 32;
inline constexpr int KEY_F1 = 290;
inline constexpr int KEY_F2 = 291;
inline constexpr int KEY_F3 = 292;
inline constexpr int KEY_F4 = 293;
inline constexpr int KEY_F5 = 294;
inline constexpr int KEY_F6 = 295;
inline constexpr int KEY_Q = 81;
inline constexpr int KEY_LEFT_BRACKET = 91;
inline constexpr int KEY_RIGHT_BRACKET = 93;
inline constexpr int KEY_M = 77;
inline constexpr int KEY_G = 71;
inline constexpr int KEY_V = 86;
inline constexpr int KEY_L = 76;
inline constexpr int KEY_F = 70;
inline constexpr int KEY_S = 83;
inline constexpr int KEY_R = 82;
inline constexpr int KEY_ENTER = 257;
inline constexpr int KEY_ESCAPE = 256;
inline constexpr int KEY_UP = 265;
inline constexpr int KEY_DOWN = 264;
inline constexpr int KEY_LEFT = 263;
inline constexpr int KEY_RIGHT = 262;
inline constexpr int KEY_PAGE_UP = 266;
inline constexpr int KEY_PAGE_DOWN = 267;
inline constexpr int KEY_HOME = 268;
inline constexpr int KEY_END = 269;
inline constexpr int KEY_BACKSPACE = 259;

Vector2 GetScreenToWorld2D(Vector2, Camera2D);
Vector2 GetWorldToScreen2D(Vector2, Camera2D);
Vector2 GetMousePosition();
Vector2 GetMouseDelta();
float GetMouseWheelMove();
int GetCharPressed();
double GetTime();
int GetScreenWidth();
int GetScreenHeight();
int GetFPS();
bool CheckCollisionPointRec(Vector2, Rectangle);
bool IsKeyPressed(int);
bool IsMouseButtonDown(int);
bool IsMouseButtonPressed(int);
bool WindowShouldClose();
void SetConfigFlags(unsigned int);
void InitWindow(int,int,const char*);
void CloseWindow();
void SetTargetFPS(int);
void SetWindowTitle(const char*);
void SetWindowMinSize(int, int);
void SetWindowSize(int, int);
int MeasureText(const char*, int);
Vector2 MeasureTextEx(Font, const char*, float, float);
Font GetFontDefault();
Font LoadFontEx(const char*, int, int*, int);
void UnloadFont(Font);
void DrawTextEx(Font, const char*, Vector2, float, float, Color);
void SetClipboardText(const char*);
void BeginDrawing();
void EndDrawing();
void ClearBackground(Color);
void BeginMode2D(Camera2D);
void EndMode2D();
void BeginScissorMode(int,int,int,int);
void EndScissorMode();
void DrawText(const char*,int,int,int,Color);
void DrawRectangle(int,int,int,int,Color);
void DrawRectangleRec(Rectangle,Color);
void DrawRectangleLinesEx(Rectangle,float,Color);
void DrawLine(int,int,int,int,Color);
void DrawLineV(Vector2,Vector2,Color);
void DrawLineEx(Vector2,Vector2,float,Color);
void DrawCircleV(Vector2,float,Color);
void DrawCircleLines(int,int,float,Color);
void DrawTriangle(Vector2,Vector2,Vector2,Color);
void DrawTexturePro(Texture2D,Rectangle,Rectangle,Vector2,float,Color);
Color Fade(Color,float);
Image GenImageColor(int,int,Color);
Texture2D LoadTextureFromImage(Image);
void UnloadImage(Image);
void UnloadTexture(Texture2D);
void UpdateTexture(Texture2D,const void*);
void SetTextureFilter(Texture2D,int);
bool IsWindowReady();
Shader LoadShaderFromMemory(const char*, const char*);
void UnloadShader(Shader);
int GetShaderLocation(Shader, const char*);
void SetShaderValue(Shader, int, const void*, int);
void BeginShaderMode(Shader);
void EndShaderMode();
Texture2D GetShapesTexture();
Rectangle GetShapesTextureRectangle();
const char* TextFormat(const char*, ...);
