#pragma once
inline constexpr int RL_LINES = 1;
inline constexpr int RL_QUADS = 7;
void rlSetTexture(unsigned int);
void rlBegin(int);
void rlEnd();
void rlNormal3f(float,float,float);
void rlColor4ub(unsigned char,unsigned char,unsigned char,unsigned char);
void rlTexCoord2f(float,float);
void rlVertex2f(float,float);

inline constexpr int RL_FLOAT = 0x1406;
inline constexpr int RL_OPENGL_21 = 2;
inline constexpr int RL_OPENGL_33 = 3;
inline constexpr int RL_OPENGL_43 = 4;
int rlGetVersion();
unsigned int rlLoadVertexArray();
bool rlEnableVertexArray(unsigned int);
void rlDisableVertexArray();
unsigned int rlLoadVertexBuffer(const void*, int, bool);
void rlUpdateVertexBuffer(unsigned int, const void*, int, int);
void rlEnableVertexBuffer(unsigned int);
void rlDisableVertexBuffer();
void rlEnableVertexAttribute(unsigned int);
void rlSetVertexAttribute(unsigned int, int, int, bool, int, int);
void rlSetVertexAttributeDivisor(unsigned int, int);
void rlDrawVertexArrayInstanced(int, int, int);
void rlUnloadVertexArray(unsigned int);
void rlUnloadVertexBuffer(unsigned int);
void rlDrawRenderBatchActive();
