from __future__ import annotations

from dataclasses import dataclass
import numpy as np

from .config import SimulationConfig


@dataclass
class GroupSummary:
    group_ids: np.ndarray
    counts: np.ndarray
    mean_energy: np.ndarray


@dataclass(frozen=True)
class RelationUpdatePlan:
    """Canonical, replayable relation events produced before world commit.

    Events are ordered by ``(owner_index, event_sequence)``.  ``source_rows``
    preserves the originating action-intent row and ``reciprocal`` marks the
    successful target-to-owner acknowledgement generated by a share.  The
    fixed-slot relation store is deliberately absent from this value, so CPU,
    GPU, distributed, and replay planners can share the same event boundary.
    """

    owner_indices: np.ndarray
    target_indices: np.ndarray
    trust_delta: np.ndarray
    familiarity_delta: np.ndarray
    source_rows: np.ndarray
    event_sequence: np.ndarray
    reciprocal: np.ndarray
    tick: int

    @property
    def size(self) -> int:
        return int(self.owner_indices.size)


def empty_relation_update_plan(tick: int) -> RelationUpdatePlan:
    """Return an empty plan with the canonical event dtypes."""
    return RelationUpdatePlan(
        owner_indices=np.empty(0, dtype=np.int32),
        target_indices=np.empty(0, dtype=np.int32),
        trust_delta=np.empty(0, dtype=np.float32),
        familiarity_delta=np.empty(0, dtype=np.float32),
        source_rows=np.empty(0, dtype=np.int32),
        event_sequence=np.empty(0, dtype=np.int64),
        reciprocal=np.empty(0, dtype=bool),
        tick=int(tick),
    )


def build_share_relation_update_plan(
    cfg: SimulationConfig,
    rows: np.ndarray,
    owners: np.ndarray,
    targets: np.ndarray,
    success: np.ndarray,
    eligible: np.ndarray,
    tick: int,
) -> RelationUpdatePlan:
    """Expand resolved shares into canonical forward/reciprocal events.

    Failed shares update trust only when the target was a valid interaction
    partner.  Invalid, dead, out-of-range, or self targets produce no relation
    event.  Successful shares additionally emit a reciprocal half-gain event.
    """
    row_values = np.asarray(rows, dtype=np.int32)
    owner_values = np.asarray(owners, dtype=np.int32)
    target_values = np.asarray(targets, dtype=np.int32)
    success_values = np.asarray(success, dtype=bool)
    eligible_values = np.asarray(eligible, dtype=bool)
    arrays = (row_values, owner_values, target_values, success_values, eligible_values)
    if any(value.ndim != 1 for value in arrays):
        raise ValueError("share relation inputs must be one-dimensional")
    if len({value.size for value in arrays}) != 1:
        raise ValueError("share relation inputs must have the same length")
    if row_values.size == 0:
        return empty_relation_update_plan(tick)

    eligible_positions = np.flatnonzero(eligible_values)
    successful_positions = np.flatnonzero(eligible_values & success_values)
    if eligible_positions.size == 0:
        return empty_relation_update_plan(tick)

    gain = np.float32(cfg.social.trust_gain_share)
    loss = np.float32(cfg.social.trust_loss_failed)
    base_sequence = np.arange(row_values.size, dtype=np.int64) * 2
    forward_delta = np.where(success_values[eligible_positions], gain, -loss).astype(np.float32)
    owner_indices = np.concatenate(
        (owner_values[eligible_positions], target_values[successful_positions])
    )
    target_indices = np.concatenate(
        (target_values[eligible_positions], owner_values[successful_positions])
    )
    trust_delta = np.concatenate(
        (
            forward_delta,
            np.full(successful_positions.size, gain * np.float32(0.5), dtype=np.float32),
        )
    )
    familiarity_delta = np.full(owner_indices.size, 0.05, dtype=np.float32)
    source_rows = np.concatenate(
        (row_values[eligible_positions], row_values[successful_positions])
    )
    event_sequence = np.concatenate(
        (base_sequence[eligible_positions], base_sequence[successful_positions] + 1)
    )
    reciprocal = np.concatenate(
        (
            np.zeros(eligible_positions.size, dtype=bool),
            np.ones(successful_positions.size, dtype=bool),
        )
    )
    order = np.lexsort((event_sequence, owner_indices))
    return RelationUpdatePlan(
        owner_indices=owner_indices[order].astype(np.int32, copy=False),
        target_indices=target_indices[order].astype(np.int32, copy=False),
        trust_delta=trust_delta[order].astype(np.float32, copy=False),
        familiarity_delta=familiarity_delta[order],
        source_rows=source_rows[order].astype(np.int32, copy=False),
        event_sequence=event_sequence[order],
        reciprocal=reciprocal[order],
        tick=int(tick),
    )


class SocialSystem:
    """Fixed-capacity relationships plus approximate connected-group detection."""

    _UNTRACKED_DECAY_TICK = np.iinfo(np.int64).min

    def __init__(self, cfg: SimulationConfig, capacity: int) -> None:
        self.cfg = cfg
        k = cfg.entities.relation_slots
        self.target = np.full((capacity, k), -1, dtype=np.int32)
        self.trust = np.zeros((capacity, k), dtype=np.float32)
        self.familiarity = np.zeros((capacity, k), dtype=np.float32)
        self.last_interaction = np.zeros((capacity, k), dtype=np.uint32)
        # Relationship values are materialized only at the rows that consume
        # them (share updates or group detection).  The stored tick is the
        # last inclusive end-of-tick decay applied to that slot.  The sentinel
        # keeps externally seeded relationship fixtures backward-compatible:
        # they begin to track decay when first updated by the simulation.
        self.last_decay_tick = np.full(
            (capacity, k), self._UNTRACKED_DECAY_TICK, dtype=np.int64
        )
        self.group_id = np.zeros(capacity, dtype=np.uint64)
        self.group_age = np.zeros(capacity, dtype=np.uint32)
        self.group_dir_x = np.zeros(capacity, dtype=np.float32)
        self.group_dir_y = np.zeros(capacity, dtype=np.float32)


    def reset_entities(self, indices: np.ndarray) -> None:
        if indices.size == 0:
            return
        self.target[indices] = -1
        self.trust[indices] = 0.0
        self.familiarity[indices] = 0.0
        self.last_interaction[indices] = 0
        self.last_decay_tick[indices] = self._UNTRACKED_DECAY_TICK
        self.group_id[indices] = 0
        self.group_age[indices] = 0
        self.group_dir_x[indices] = 0.0
        self.group_dir_y[indices] = 0.0

    def _materialize_decay(
        self,
        rows: np.ndarray,
        through_tick: int,
        *,
        assume_unique: bool = False,
    ) -> None:
        """Apply deferred geometric decay through an inclusive tick boundary."""
        owner_rows = np.asarray(rows, dtype=np.int32)
        if owner_rows.size == 0:
            return
        if not assume_unique:
            owner_rows = np.unique(owner_rows)
        last = self.last_decay_tick[owner_rows]
        tracked = last != self._UNTRACKED_DECAY_TICK
        if not np.any(tracked):
            return
        elapsed = np.maximum(int(through_tick) - last, 0)
        apply = tracked & (elapsed > 0)
        if np.any(apply):
            factor = np.float32(max(0.0, 1.0 - self.cfg.social.relation_decay))
            decay = np.ones(last.shape, dtype=np.float32)
            decay[apply] = np.power(factor, elapsed[apply], dtype=np.float32)
            self.trust[owner_rows] *= decay
            self.familiarity[owner_rows] *= decay
        last[tracked] = int(through_tick)
        self.last_decay_tick[owner_rows] = last

    def decay(self, alive: np.ndarray) -> None:
        """Eager compatibility operation for callers outside the main loop.

        The simulation uses :meth:`_materialize_decay` at read/write
        boundaries instead, avoiding full relation-table passes on ticks with
        no social interaction or group recomputation.
        """
        factor = max(0.0, 1.0 - self.cfg.social.relation_decay)
        self.trust[alive] *= factor
        self.familiarity[alive] *= factor

    def _update_one(self, owner: int, target: int, trust_delta: float, tick: int) -> None:
        if owner < 0 or target < 0 or owner == target:
            return
        row_targets = self.target[owner]
        existing = np.flatnonzero(row_targets == target)
        if existing.size:
            slot = int(existing[0])
        else:
            empty = np.flatnonzero(row_targets < 0)
            if empty.size:
                slot = int(empty[0])
            else:
                # Keep important and recent ties; replace the weakest effective slot.
                score = self.trust[owner] + 0.25 * self.familiarity[owner]
                slot = int(np.argmin(score))
            self.target[owner, slot] = target
            self.trust[owner, slot] = 0.0
            self.familiarity[owner, slot] = 0.0
        self.trust[owner, slot] = np.clip(self.trust[owner, slot] + trust_delta, 0.0, 1.0)
        self.familiarity[owner, slot] = np.clip(self.familiarity[owner, slot] + 0.05, 0.0, 1.0)
        self.last_interaction[owner, slot] = tick

    def _update_unique_owners(
        self,
        owners: np.ndarray,
        targets: np.ndarray,
        trust_delta: np.ndarray,
        familiarity_delta: np.ndarray,
        tick: int,
    ) -> None:
        """Apply one event for each distinct owner in a vectorized batch."""
        if owners.size == 0:
            return
        row_targets = self.target[owners]
        existing_matches = row_targets == targets[:, None]
        existing = existing_matches.any(axis=1)
        existing_slot = existing_matches.argmax(axis=1)
        empty = row_targets < 0
        has_empty = empty.any(axis=1)
        empty_slot = empty.argmax(axis=1)
        slots = np.where(existing, existing_slot, empty_slot).astype(np.int32)
        needs_replacement = ~existing & ~has_empty
        if np.any(needs_replacement):
            replacement_owners = owners[needs_replacement]
            slots[needs_replacement] = (
                self.trust[replacement_owners]
                + np.float32(0.25) * self.familiarity[replacement_owners]
            ).argmin(axis=1)
        new_relation = ~existing
        if np.any(new_relation):
            inserted_owners = owners[new_relation]
            inserted_slots = slots[new_relation]
            self.target[inserted_owners, inserted_slots] = targets[new_relation]
            self.trust[inserted_owners, inserted_slots] = 0.0
            self.familiarity[inserted_owners, inserted_slots] = 0.0
        self.trust[owners, slots] = np.clip(self.trust[owners, slots] + trust_delta, 0.0, 1.0)
        self.familiarity[owners, slots] = np.clip(
            self.familiarity[owners, slots] + familiarity_delta, 0.0, 1.0
        )
        self.last_interaction[owners, slots] = tick
        # This relation has just been updated before the end-of-tick decay.
        # At a later consumer boundary, ``tick - 1`` therefore denotes the
        # last decay already reflected in its stored value.
        self.last_decay_tick[owners, slots] = int(tick) - 1

    def apply_relation_updates(self, plan: RelationUpdatePlan) -> None:
        """Apply one canonical event plan in owner-local stable order.

        Relation rows are independent: reordering updates for different
        owners cannot affect the result, while updates to one owner must keep
        their original event sequence because a full row may replace its
        weakest slot.  Events are therefore processed in owner-local rank
        order, with each rank forming a vectorized batch of distinct owners.
        """
        owner_values = np.asarray(plan.owner_indices, dtype=np.int32)
        target_values = np.asarray(plan.target_indices, dtype=np.int32)
        trust_delta = np.asarray(plan.trust_delta, dtype=np.float32)
        familiarity_delta = np.asarray(plan.familiarity_delta, dtype=np.float32)
        source_rows = np.asarray(plan.source_rows, dtype=np.int32)
        event_sequence = np.asarray(plan.event_sequence, dtype=np.int64)
        reciprocal = np.asarray(plan.reciprocal, dtype=bool)
        arrays = (
            owner_values,
            target_values,
            trust_delta,
            familiarity_delta,
            source_rows,
            event_sequence,
            reciprocal,
        )
        if any(value.ndim != 1 for value in arrays):
            raise ValueError("relation update plan arrays must be one-dimensional")
        if len({value.size for value in arrays}) != 1:
            raise ValueError("relation update plan arrays must have the same length")
        if owner_values.size == 0:
            return
        if int(plan.tick) < 0:
            raise ValueError("relation update plan tick must be non-negative")
        capacity = self.target.shape[0]
        if (
            np.any(owner_values < 0)
            or np.any(owner_values >= capacity)
            or np.any(target_values < 0)
            or np.any(target_values >= capacity)
            or np.any(owner_values == target_values)
        ):
            raise ValueError("relation update plan contains an invalid owner/target pair")
        if np.any(source_rows < 0) or np.any(event_sequence < 0):
            raise ValueError("relation update plan contains invalid provenance")
        if not np.all(np.isfinite(trust_delta)) or not np.all(np.isfinite(familiarity_delta)):
            raise ValueError("relation update plan deltas must be finite")
        owner_ordered = owner_values[1:] >= owner_values[:-1]
        sequence_ordered = (owner_values[1:] != owner_values[:-1]) | (
            event_sequence[1:] >= event_sequence[:-1]
        )
        if not np.all(owner_ordered & sequence_ordered):
            raise ValueError("relation update plan must be ordered by owner and event sequence")

        # A relationship may be untouched for many ticks.  Materialize only
        # the owner rows that are about to compare, replace, or update slots;
        # their effective values then exactly match the eager schedule at the
        # start of this tick.
        starts = np.concatenate(
            (
                np.asarray([0], dtype=np.int64),
                np.flatnonzero(owner_values[1:] != owner_values[:-1]).astype(np.int64) + 1,
            )
        )
        counts = np.diff(
            np.concatenate((starts, np.asarray([owner_values.size], dtype=np.int64)))
        )
        unique_owners = owner_values[starts]
        self._materialize_decay(
            unique_owners,
            int(plan.tick) - 1,
            assume_unique=True,
        )
        # Each pass contains exactly one event per owner.  Processing the
        # passes in rank order retains the scalar replacement semantics even
        # when several events target one owner in the same tick.
        for event_rank in range(int(counts.max())):
            active_owners = counts > event_rank
            positions = starts[active_owners] + event_rank
            self._update_unique_owners(
                owner_values[positions],
                target_values[positions],
                trust_delta[positions],
                familiarity_delta[positions],
                int(plan.tick),
            )

    def record_shares(self, owners: np.ndarray, targets: np.ndarray, success: np.ndarray, tick: int) -> None:
        """Backward-compatible share-event convenience wrapper."""
        owner_values = np.asarray(owners, dtype=np.int32)
        target_values = np.asarray(targets, dtype=np.int32)
        success_values = np.asarray(success, dtype=bool)
        plan = build_share_relation_update_plan(
            self.cfg,
            rows=np.arange(owner_values.size, dtype=np.int32),
            owners=owner_values,
            targets=target_values,
            success=success_values,
            eligible=(owner_values >= 0) & (target_values >= 0) & (owner_values != target_values),
            tick=tick,
        )
        self.apply_relation_updates(plan)

    def clear_dead_targets(self, alive: np.ndarray) -> None:
        valid_target = self.target >= 0
        dead_link = valid_target & ~alive[np.where(valid_target, self.target, 0)]
        self.target[dead_link] = -1
        self.trust[dead_link] = 0.0
        self.familiarity[dead_link] = 0.0
        self.last_decay_tick[dead_link] = self._UNTRACKED_DECAY_TICK

    def update_groups(
        self,
        alive: np.ndarray,
        stable_ids: np.ndarray,
        energy: np.ndarray,
        resource_grad_x: np.ndarray,
        resource_grad_y: np.ndarray,
        tick: int,
    ) -> GroupSummary:
        active = np.flatnonzero(alive).astype(np.int32)
        if active.size == 0:
            self.group_id.fill(0)
            return GroupSummary(np.empty(0, dtype=np.uint64), np.empty(0, dtype=np.int32), np.empty(0, dtype=np.float32))

        # Group detection is the other relationship consumer.  Deferring
        # decay until this lower-frequency boundary preserves the intended
        # geometric rule without a full O(N*K) pass every world tick.
        self._materialize_decay(active, tick, assume_unique=True)
        labels = np.arange(alive.size, dtype=np.int32)
        trusted = (self.target >= 0) & (self.trust >= self.cfg.social.trust_group_threshold)
        # Label propagation is approximate but vectorizable and deterministic.
        for _ in range(8):
            new_labels = labels.copy()
            for slot in range(self.target.shape[1]):
                target = self.target[:, slot]
                valid = trusted[:, slot] & alive & (target >= 0)
                safe_target = np.where(valid, target, 0)
                candidate = labels[safe_target]
                new_labels = np.where(valid, np.minimum(new_labels, candidate), new_labels)
            labels = new_labels

        roots = labels[active]
        unique_roots, inverse, counts = np.unique(roots, return_inverse=True, return_counts=True)
        valid_group = counts >= self.cfg.social.group_min_members
        root_to_group = np.zeros(unique_roots.size, dtype=np.uint64)
        root_to_group[valid_group] = stable_ids[unique_roots[valid_group]]
        new_group = root_to_group[inverse]

        old = self.group_id[active].copy()
        self.group_id[active] = new_group
        same = old == new_group
        self.group_age[active] = np.where((new_group != 0) & same, self.group_age[active] + 1, np.where(new_group != 0, 1, 0))
        self.group_dir_x[active] = 0.0
        self.group_dir_y[active] = 0.0

        valid_members = new_group != 0
        if np.any(valid_members):
            group_values, group_inverse = np.unique(new_group[valid_members], return_inverse=True)
            member_indices = active[valid_members]
            sums_x = np.bincount(group_inverse, weights=resource_grad_x[member_indices], minlength=group_values.size)
            sums_y = np.bincount(group_inverse, weights=resource_grad_y[member_indices], minlength=group_values.size)
            member_counts = np.bincount(group_inverse, minlength=group_values.size)
            dx = sums_x / np.maximum(member_counts, 1)
            dy = sums_y / np.maximum(member_counts, 1)
            norm = np.maximum(np.hypot(dx, dy), 1e-6)
            dx /= norm
            dy /= norm
            self.group_dir_x[member_indices] = dx[group_inverse].astype(np.float32)
            self.group_dir_y[member_indices] = dy[group_inverse].astype(np.float32)
            mean_energy = np.bincount(group_inverse, weights=energy[member_indices], minlength=group_values.size) / np.maximum(member_counts, 1)
            return GroupSummary(group_values, member_counts.astype(np.int32), mean_energy.astype(np.float32))

        return GroupSummary(np.empty(0, dtype=np.uint64), np.empty(0, dtype=np.int32), np.empty(0, dtype=np.float32))
